### ISSUE TITLE
有在做 nrm 相关的功能吗，没有的话，想来提 pr 了

### ISSUE THREAD

**Issue by rottenpen** [appworks-lab/toolkit#27]
。

**Comment by fyangstudio** [comment]
感谢反馈，目前在插件设置中有切换的选项。这个功能能满足需求吗？

![image](https://user-images.githubusercontent.com/9896768/121113783-37d5f700-c845-11eb-8f46-0ef289dec6f8.png)

**Comment by rottenpen** [comment]
1. 感觉这个入口做的太深了，作为用户我会选择 `nrm use xxx`
2. 目前市面上的方案好像都没有考虑 yarn(yarn会自动用 npm 的设置 可以忽略)/ cnpm / pnpm 的配置

**Comment by luhc228** [comment]
> 1. 感觉这个入口做的太深了，作为用户我会选择 `nrm use xxx`
> 2. 目前市面上的方案好像都没有考虑 yarn(yarn会自动用 npm 的设置 可以忽略)/ cnpm / pnpm 的配置

有规划做这两个功能，其实是就是把 nrm 脚手架和 包管理工具的可视化

**Comment by rottenpen** [comment]
> > 1. 感觉这个入口做的太深了，作为用户我会选择 `nrm use xxx`
> > 2. 目前市面上的方案好像都没有考虑 yarn(yarn会自动用 npm 的设置 可以忽略)/ cnpm / pnpm 的配置
> 
> 有规划做这两个功能，其实是就是把 nrm 脚手架和 包管理工具的可视化

欢迎pr吗

**Comment by luhc228** [comment]
> > > 1. 感觉这个入口做的太深了，作为用户我会选择 `nrm use xxx`
> > > 2. 目前市面上的方案好像都没有考虑 yarn(yarn会自动用 npm 的设置 可以忽略)/ cnpm / pnpm 的配置
> > 
> > 
> > 有规划做这两个功能，其实是就是把 nrm 脚手架和 包管理工具的可视化
> 
> 欢迎pr吗

Welcome

**Comment by luhc228** [comment]
发布 0.2.0 版本已实现
