### ISSUE TITLE
appworks相关文档打不开

### ISSUE THREAD

**Issue by 1391020381** [appworks-lab/toolkit#28]
https://appworks.site/

**Comment by GiveMe-A-Name** [comment]
具体指哪篇文档，能给出相应的url吗

**Comment by GiveMe-A-Name** [comment]
指的是https://appworks.site/网站打不开吗，还是具体的哪篇文档？可以给出相应的url链接

**Comment by 1391020381** [comment]
> 指的是 https://appworks.site/ 网站打不开吗，还是具体的哪篇文档？可以给出相应的url链接
是的，上午打不开。。。。。。。

**Comment by 1391020381** [comment]
https://work.def.alibaba-inc.com/doc/index 这个网址还是打不开

**Comment by fyangstudio** [comment]
![image](https://user-images.githubusercontent.com/9896768/121130012-5c8b9800-c860-11eb-8982-f2b91a598cea.png)
感谢您对 AppWorks 的支持，文档是从这里点击的吗？  

这个是阿里内网可以访问的链接，我们会备注下 仅阿里内网可访问

**Comment by 1391020381** [comment]
。。。。。。。。。。。。。。。。。

**Comment by 1391020381** [comment]
。。。。。。。。。。。。。。。。。。。
